### ISSUE TITLE
Баг

### ISSUE THREAD

**Issue by lgnv** [KathrinM13/olympmath_ekb_bot#10]
https://github.com/KathrinM13/olympmath_ekb_bot/blob/e6e080b91206beeb9e5eda14f015bad4ea5e1d33/src/main/java/handlers/ChooseThemeHandler.java#L29

в этом методе у тебя баг, попробуй сама найти его

**Comment by KathrinM13** [comment]
А ты уверен, что не принял фичу за баг?...

**Comment by lgnv** [comment]
кейс: 
у тебя для 8 и 9 класса есть тема, допустим "Уравнение"
у пользователя выбран 9 класс 
Тут, допустим выберется тема для 8 класса, так как отсортированы: 
```
Theme theme = themes.getAll().stream()
				.filter(th -> th.getName().equalsIgnoreCase(update.getMessage()))
				.findAny()
				.orElse(null);
```
эта проверка выдаст `false`: 
```
if(theme != null && theme.getGrade() == user.getGrade()) 
```
и ты скажешь пользователю про ошибку
