### ISSUE TITLE
Потерянный переход состояния

### ISSUE THREAD

**Issue by lgnv** [KathrinM13/olympmath_ekb_bot#14]
https://github.com/KathrinM13/olympmath_ekb_bot/blob/e6e080b91206beeb9e5eda14f015bad4ea5e1d33/src/main/java/handlers/SolveTaskHandler.java#L24

после этой команды пользователь так и остается в состоянии решения задачи?

**Comment by KathrinM13** [comment]
В коде, который пока не закоммитен, уже нет)
