### ISSUE TITLE
Бот зависим от телеграмма

### ISSUE THREAD

**Issue by lgnv** [KathrinM13/olympmath_ekb_bot#3]
https://github.com/KathrinM13/olympmath_ekb_bot/blob/e6e080b91206beeb9e5eda14f015bad4ea5e1d33/src/main/java/models/Bot.java#L8

важно, чтобы логика бота не была привязана к платформе(в данном случае к телеграму) 
сейчас привязана, убери 

для проверки: реализуй возможность работы бота через консоль

**Comment by KathrinM13** [comment]
Вся логика бота находится в классе UpdateReceiver, и я могу реализовать бота для консоли следующим образом:
![image](https://user-images.githubusercontent.com/81215935/225055861-216169b5-f177-494f-8d64-276d6d03484f.png)

Тут большая часть кода этот инициализации, а сам диалог в цикле while

**Comment by KathrinM13** [comment]
Вот код с точно такой же иницализацией, но вместо диалога в цикле while, в конце мы запускаем бота уже конкретно в тг, он работает как раз благодаря тому, что Bot, который зависит от тг, принимает на вход экземпляр UpdateReceiver`а, который и реализует всю логику
![image](https://user-images.githubusercontent.com/81215935/225058535-acb93f25-3b5e-408e-8b2c-14d360b3f354.png)

**Comment by lgnv** [comment]
wrappedupdate у тебя зависит от телеграма
а значит и консольная версия будет зависеть

**Comment by KathrinM13** [comment]
Нет, у WrappedUpdate два конструктора, один из них никак не привязан к тг
