### ISSUE TITLE
Магические числа

### ISSUE THREAD

**Issue by lgnv** [KathrinM13/olympmath_ekb_bot#6]
https://github.com/KathrinM13/olympmath_ekb_bot/blob/e6e080b91206beeb9e5eda14f015bad4ea5e1d33/src/main/java/handlers/ChoseeTaskOrTheoryHandler.java#L41

что значит 1? 2?

**Comment by KathrinM13** [comment]
Ну тут реализуется, выбор из двух вариантов: решать задачу или читать теорию. Могу написать комментарий))

**Comment by lgnv** [comment]
комментарии лучше не писать
на них нечасто смотрят при большом количестве кода 
эти 1, 2 могу просочиться в места где не будет этого комментарий
кто то добавит 3 и забудет обновить комментарий 

так что лучше код писать так, чтобы было понятно что делается, без магических констант прям в коде
