### ISSUE TITLE
Беспорядок?

### ISSUE THREAD

**Issue by lgnv** [KathrinM13/olympmath_ekb_bot#9]
https://github.com/KathrinM13/olympmath_ekb_bot/blob/e6e080b91206beeb9e5eda14f015bad4ea5e1d33/src/main/java/models/Bot.java#L60

**Comment by KathrinM13** [comment]
Я не понимаю, что ты имеешь ввиду

**Comment by lgnv** [comment]
mess - беспорядок 
непонятный нейминг переменных
